### ISSUE TITLE
Publica no Package Control

### ISSUE THREAD

**Issue by felquis** [MageFront/MagentoSnippets#1]
Para publicar basta [seguir esses passos](https://packagecontrol.io/docs/submitting_a_package), [aqui](https://packagecontrol.io/docs) tem alguns links legais tbm. :)

**Comment by vanessametonini** [comment]
Ha, obrigada pelas dicas, vou juntar mais alguns Snippets para assim publicar.

**Comment by vanessametonini** [comment]
Done! https://packagecontrol.io/packages/MagentoSnippets
and thanks!

**Comment by vanessametonini** [comment]
Done! https://packagecontrol.io/packages/MagentoSnippets
and thanks!
