### ISSUE TITLE
"mg-anon-func-jquery" do not work!

### ISSUE THREAD

**Issue by rafaelstz** [MageFront/MagentoSnippets#12]
Snippet **mg-anon-func-jquery** don't work!

**Comment by vanessametonini** [comment]
Hi Rafael! Thanks for open this issue! Please fell free to pull request the fix to that :)
Check the [contribution text](https://github.com/MageFront/MagentoSnippets/blob/master/contribute.md) to check how to do that.

**Comment by nathpaiva** [comment]
Doesn't exist anymore? :|

**Comment by vanessametonini** [comment]
I renamed it to 'iife' ;)
