### ISSUE TITLE
Em alguns snippets o $this não aparece

### ISSUE THREAD

**Issue by nathpaiva** [MageFront/MagentoSnippets#4]
Quando fui utilizar o snippets de bloco estático no sublime ele não colocou o $this antes, ficando dessa forma:

<?php echo ->getLayout()->createBlock('cms/block')->setBlockId('')->toHtml(); ?>

**Comment by felquis** [comment]
No snippets o $ é um caractere reservado, você precisa escapar o caractere com \

``` php
\$('.test')
```

[Igual aqui](https://github.com/felquis/ionic-sublime-plugin/blob/master/js/popup/ionic-popup-confirm.sublime-snippet#L3-L4)

cc @vanessametonini

**Comment by vanessametonini** [comment]
Hmm! Imaginei que fosse isso, só não sabia como que era o escape, se era normal com a barra
obrigada pela contribuição @felquis :)
